// Generated by https://quicktype.io

import { User } from "./User";


export interface Tasks {
    tasks: TaskElement[];
}

export interface TaskElement {
    id:          string;
    description: string;
    status:      string;
    isActive:    boolean;
    user:        User;
}

