// Generated by https://quicktype.io

export interface User {
    name:     string;
    lastname: string;
    user:     string;
    email:    string;
    roles:    string[];
    id:       string;
    isActive: boolean;
    token:    string;
}


export interface LoginUser{
    email: string;
    password: string;
}